language: node_js
node_js:
  - "10"
dist: trusty

sudo: required
addons:
  chrome: stable

branches:
  only:
  - master

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run build -- --aot --prod --build-optimizer --base-href /project-private-showcase-front/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/private-showcase
  on:
    branch: master
